# Generated by Django 2.2.4 on 2019-09-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190929_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_suspend',
        ),
    ]
