# Generated by Django 2.2.4 on 2019-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_is_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_suspend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
